### ISSUE TITLE
Data Repositories

### ISSUE THREAD

**Issue by prisae** [softwareunderground/awesome-open-geoscience#126]
What is the intended extent of https://github.com/softwareunderground/awesome-open-geoscience#data-repositories?

Like, should there go things like
- https://wiki.seg.org/wiki/Open_data
- or Equinor-Volve?

**Comment by JustinGOSSES** [comment]
yes

**Comment by prisae** [comment]
OK. Made a PR for the SEG Catalog (https://github.com/softwareunderground/awesome-open-geoscience/pull/138) - I've never used Volve nor been on the website, so I won't do that one.
