### ISSUE TITLE
pyrocko link superseded

### ISSUE THREAD

**Issue by da-wad** [softwareunderground/awesome-open-geoscience#136]
Link for Pyrocko should point here: https://git.pyrocko.org/pyrocko/pyrocko rather than here https://github.com/pyrocko/pyrocko

**Comment by KerinPithawala** [comment]
Can I work on this issue?

**Comment by JustinGOSSES** [comment]
@KerinPithawala absolutely

**Comment by JustinGOSSES** [comment]
Thanks @KerinPithawala 

Your issue is closed @da-wad
