### ISSUE TITLE
Geoscience softwares

### ISSUE THREAD

**Issue by anakletus** [softwareunderground/awesome-open-geoscience#143]

**Comment by anakletus** [comment]
Helpful software platforms for Petroleum engineers

**Comment by JustinGOSSES** [comment]
Probably out of scope for this awesome list? But would be great to link to under reservoir engineering if someone wanted to start that awesome list. I searched quickly and didn't find one already started.

**Comment by JustinGOSSES** [comment]
Leaving this common open to inspire others who might be interested.
