### ISSUE TITLE
rename default branch to `main`

### ISSUE THREAD

**Issue by amoodie** [softwareunderground/awesome-open-geoscience#163]
Suggestion to rename the default branch of the repository to `main`.

[Very straightforward to do](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch), just would want approval from a few folks (e.g., @JustinGOSSES, @kwinkunks).

**Comment by JustinGOSSES** [comment]
Good suggestion

**Comment by JustinGOSSES** [comment]
Done
