### ISSUE TITLE
Add DOI badge

### ISSUE THREAD

**Issue by JustinGOSSES** [softwareunderground/awesome-open-geoscience#202]
Add the DOI badge to README and attempt to auto modify a citation file via GitHub actions 

https://doi.org/10.5281/zenodo.8354180

**Comment by JustinGOSSES** [comment]
Reminder @JustinGOSSES

**Comment by JustinGOSSES** [comment]
Addressed by https://github.com/softwareunderground/awesome-open-geoscience/pull/205 so this can be closed when that PR is approved & merged

**Comment by mmcint** [comment]
PR #205 was approved and merged
