### ISSUE TITLE
Maintain app

### ISSUE THREAD

**Issue by mmcint** [softwareunderground/awesome-open-geoscience#208]
### Contact Details

m.mcintire00@gmail.com

### Why

I enjoy this list and frequently use it as reference. I’m relatively new to SWUNG and want to get more involved. I also want to learn maintainer skills.

### How have you participated

```shell
I’m relatively new to swung (about 1yr). I participate in discussions on the slack/Mattermost channels. I frequently use the resources on this repo for my daily work as a geo data scientist @ThinkOnward (formerly Studio X).

I’m a geoscientist by education, with a BS and MS from Kansas State. I worked as a geophysicist at APC/OXY from 2014-2021 in the GoM. I left to pursue an opportunity in data science.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustinGOSSES** [comment]
Sweet, welcome @mmcint . I added you to the awesome team, so you should have permissions to approve PRs.

There’s a few open PRs. I’m going to suggest an order to get a few experiences out of the way for you as a new maintainer. 

1. Approve the DOO badge PR first. I suspect you can approve it without any merge conflicts https://github.com/softwareunderground/awesome-open-geoscience/pull/205
2. Approving that PR will probably make others in que out of date, which will give you a chance to fix the conflicts. Your PR https://github.com/softwareunderground/awesome-open-geoscience/pull/209 will likely say needs updating after step 1. Makes changes and then I’ll approve & merge. We try to only approve our own PRs in cases where debugging an issue.
3. Last, update someone else’s PR and confirm their content is awesome with the remaining PR https://github.com/softwareunderground/awesome-open-geoscience/pull/207

**Comment by JustinGOSSES** [comment]
If you run into problems or have questions, you can use this issue or Mattermost DM as makes sense for you.

**Comment by mmcint** [comment]
Sweet. Thanks Justin!
