### ISSUE TITLE
SciKit-GStat for vetting

### ISSUE THREAD

**Issue by EvanBianco** [softwareunderground/awesome-open-geoscience#40]
Found a new-ish library called SciKit-GStat, for variogram type calcuations.

https://mmaelicke.github.io/scikit-gstat/index.html

Deserves a review for the Geostats category.

**Comment by mycarta** [comment]
Loos very promising. Although I am eager to see the kriging and simulation parts see the light, I am also glad to seethe commitment to the variogram part.

**Comment by JustinGOSSES** [comment]
Has been added
