### ISSUE TITLE
Testing for broken links?

### ISSUE THREAD

**Issue by banesullivan** [softwareunderground/awesome-open-geoscience#43]
It should be possible to build a script that parses the README for all the links then checks those links... could this be implemented on Travis?

Noticed `colorcet` has a broken link and thought of this

**Comment by leouieda** [comment]
It's possible and we can set nightly cron jobs in Travis. I don't know of any good link checker for Markdown but I'm sure it exists.

**Comment by banesullivan** [comment]
This seems promising: https://github.com/dkhamsing/awesome_bot

**Comment by JesperDramsch** [comment]
@banesullivan that is a great find. I set up the infrastructure.

**Comment by banesullivan** [comment]
Awesome! Should there be a Travis badge somewhere?

**Comment by JesperDramsch** [comment]
I'm not sure. I'll leave this to decide for others. I'll go about fixing the links and redirects now.

**Comment by leouieda** [comment]
Thanks @JesperDramsch! I just protected the master branch so only pull requests that pass Travis builds can be merged.

I think we could add a travis badge to the README. I'll open a PR for that.
