### ISSUE TITLE
GeologicPatterns without License

### ISSUE THREAD

**Issue by JesperDramsch** [softwareunderground/awesome-open-geoscience#51]
The GeologicPatterns library does not seem to have a license, we should remove it for now and wait for it to have a proper open license.

**Comment by JesperDramsch** [comment]
Removed temporarily and re-added in #53

**Comment by JesperDramsch** [comment]
Adressed in https://github.com/davenquinn/geologic-patterns/issues/2

**Comment by kwinkunks** [comment]
Sorry I didn't spot this before. For the record, US Federal Gov't products are not copyrightable and therefore cannot be licensed. In any case, I see he added a public domain statement, which definitely helps.

**Comment by JesperDramsch** [comment]
I'm guessing derivative works can though, @kwinkunks?

**Comment by kwinkunks** [comment]
Yes, in principle you can do anything with public domain works. There are no restrictions or requirements. In practice, there are a few things that would be unethical...

**Comment by JesperDramsch** [comment]
Ok

Am Mo., 27. Mai 2019 um 15:44 Uhr schrieb Matt Hall <
notifications@github.com>:

**Comment by JustinGOSSES** [comment]
@kwinkunks  You made this statement:

 `For the record, US Federal Gov't products are not copyrightable and therefore cannot be licensed`. 

That isn't quite right. Many Federal government agencies release code with licenses all the time. Maybe I misunderstood it? Maybe you meant in the case where no license is explicitly included? 

For examples, check out https://code.gov/ . You can use their API to create aggregate views of the different licenses in code released by US federal agencies as shown in this Observable notebook for just NASA. https://observablehq.com/@justingosses/licenses-of-open-source-nasa-code-projects-on-code-gov

**Comment by kwinkunks** [comment]
It's a fair point, you're right: they do sometimes assert copyright, especially if non-federal workers were involved, which they often are. So I guess public domain is the default.
