### ISSUE TITLE
Icons not shown Ubuntu/Firefox

### ISSUE THREAD

**Issue by prisae** [softwareunderground/awesome-open-geoscience#58]
Most icons are not shown on Firefox (Ubuntu 18.04, Firefox 65). They are shown on Chrome (73).

### Firefox
![firefox](https://user-images.githubusercontent.com/8020943/54343323-d2333a00-463e-11e9-987a-6dce9346e1b5.png) 

### Chrome
![chrome](https://user-images.githubusercontent.com/8020943/54343322-d1020d00-463e-11e9-8f36-1618e301049f.png)

**Comment by prisae** [comment]
Something with the SVG's. From the GitLab Markdown Manual:

To insert images to your markdown file, use the markup ![ALT](/path/image.ext). The path can either be relative to the website, or a full URL for an external image. The supported formats are .png, .jpg, .gif. **You might be able to use some .svg files too, depending on its structure.**

So it seems straight forward with png/jpg/gif, but not with svg.

**Comment by prisae** [comment]
Any particular reason to use svg's here? They won't be scaled, so I guess we could simply use jpg's or png's.

**Comment by JesperDramsch** [comment]
That is a good point. Could probably just mogrify the whole bunch to png

**Comment by prisae** [comment]
It's probably the easiest solution.

**Comment by JesperDramsch** [comment]
Switched in #59

**Comment by JesperDramsch** [comment]
@prisae How does it look like now?

**Comment by prisae** [comment]
All good!
