### ISSUE TITLE
What makes for an "awesome" dataset?

### ISSUE THREAD

**Issue by JustinGOSSES** [softwareunderground/awesome-open-geoscience#6]
Would it be worthwhile to a sub-category to datasets along the lines of "data in bulk", "bulk download available", or "machine-learning ready"?

A lot of the open datasets out there take a lot human typing to extract large enough datasets to do something with. Wells, especially, have this problem.  

Alternatively, should we limit "awesome" datasets to those that don't take a lot of prep or extraction to get working with?

**Comment by mtb-za** [comment]
I would favour "awesome" datasets as being those that are easy to work with, or really are just too awesome to ignore.

**Comment by JesperDramsch** [comment]
I think we can grow it organically. I'm not sure if there are enough awesome data to create the mold up front. It's supposed to be awesome after all

**Comment by JustinGOSSES** [comment]
Jesper has a good point about not creating a mold up front, maybe we encourage people to define what the dataset is "awesome" in the readme somewhere? It would be helpful to know why its a really cool dataset and not just what is in the dataset.

Perhaps under the section title we add "Please describe what is 'awesome' about each dataset  not just what is in the dataset."

**Comment by JesperDramsch** [comment]
Maybe it's even enough to give a little "awesome description" in the PR?

People coming to the list expect awesome content, so the content might be enough for them to click through, with us having vetted the awesome-ness threshold. (I'd like to keep the descriptions on the list as short as possible).
