### ISSUE TITLE
climate / ocean / weather in scope?

### ISSUE THREAD

**Issue by rabernat** [softwareunderground/awesome-open-geoscience#60]
Thanks for maintaining this amazing list!

Your list is heavy on the solid-earth side of geosciences. Are packages for climate / ocean / atmospheric science in scope? If so, I can make a PR with some suggestions?

FYI, I come from the [pangeo project](http://pangeo.io) and found this list via @lheagy.

**Comment by lheagy** [comment]
I think it could be a nice way to promote more overlap between the solid earth and climate science communities, so :+1: from me!

**Comment by JesperDramsch** [comment]
Welcome @rabernat. 

Personally, I'd love to see these kinds of contributions.

**Comment by kwinkunks** [comment]
Hm... not sure. I've seen solid-earth stuff get swamped before by fluid-earth stuff (I'm thinking of Earth Science Stack Exchange for example). Maybe if there was a more nuanced way to build a list like this -- without maybe having to build a whole app, though that would obviously work -- then we could have search, filtering with categories / tags and so on. Doing it in the wiki (which I need to rescue from some sort of cert problem) could be one way to experiment with this?

**Comment by lheagy** [comment]
Would starting an `awesome-open-climate-science` or `awesome-open-fluid-earth` companion list be a good trajectory forward? We can cross-link them both so that it is clear they are related. And we can figure out another solution for searching / filtering once we have started to assembled the lists. 

cc @rabernat: have you seen a list like this for climate / ocean / weather? We don't want to duplicate efforts if one has already been started

**Comment by JustinGOSSES** [comment]
Suggest we start a new category called "Related Awesome" for things like "Awesome Geospatial" and "Awesome Climate". 

In addition to listing the link, perhaps list 1? thing from related list that would be of interest to "awesome-open-geoscience" people, so they can get a flavor for what would be related.

**Comment by JesperDramsch** [comment]
> cc @rabernat: have you seen a list like this for climate / ocean / weather? We don't want to duplicate efforts if one has already been started
I could not find anything yet, but it's possible I don't have the right keywords.

> Would starting an `awesome-open-climate-science` or `awesome-open-fluid-earth` companion list be a good trajectory forward? We can cross-link them both so that it is clear they are related. And we can figure out another solution for searching / filtering once we have started to assembled the lists.

Since we have travis for automatic link checking, I believe it should be possible to do automatic checking if a link is present in the other awesome list. But maybe I misunderstood what you meant with searching/filtering. 

In the end awesome lists are supposed to be static and excel in their structure so you can find everything. So I get the thoughts about scope. Our entire TOC is maintained by hand, which can be a bit cumbersome for us maintainers.

**Comment by leouieda** [comment]
I like the idea of an "awesome open climate science" :+1:  We could host and get it started based on this list. 

> I've seen solid-earth stuff get swamped before by fluid-earth stuff

Yep. It's hard when there are a clear minority of software minded folks in some fields. It's like how in solid earth, everything ends up being seismology. 

@rabernat @lheagy would you think of listing things like xarray? It has a strong geoscience influence but it's technically general purpose. Maybe we could restrict the lists to only discipline specific things to avoid duplication.

@kwinkunks could we have tiered lists? One for general purpose "geo" in the broad sense that links to specific ones for "solid" and "fluid"? Might be too much abstraction.

**Comment by rabernat** [comment]
Thanks for all the great discussion everyone?

I appreciate the sentiment that this list is focused on the solid earth community. There is a challenge in terminology here, because, to me, "geoscience" encompasses all of Earth science, including the fluid part. Regardless of this, I see that it makes sense to maintain this repo with its current focus and to start a new one for the atmosphere / ocean / climate / weather community.

> have you seen a list like this for climate / ocean / weather? We don't want to duplicate efforts if one has already been started

[This](http://pyaos.johnny-lin.com/?page_id=20) is one resource, but it looks a bit stale. Starting fresh would be a good idea I think.

> would you think of listing things like xarray?

It's hard for me to imagine this list not including xarray. Yes, it is general purpose. But it is also _the most useful tool_ for climate science. Other packages would be things like eofs, cartopy, aospy, metpy, gsw, satpy, etc. There would definitely be some overlap with this list, particularly around mapping.

> We could host and get it started based on this list.

That's a nice offer. It might also make sense to have it live in the pangeo-data org.

**Comment by leouieda** [comment]
> "geoscience" encompasses all of Earth science, including the fluid part

The "geo" terminology is way overcomplicated and hard to be inclusive. The planetary folks feel left out of the "geo" and geospatial/geography often claim all the catchy "geo"-something names :) We could add a disclaimer message saying that this list is dedicated to the solid earth side but checkout these other awesome lists.

>  But it is also the most useful tool for climate science.

I agree. It's by far my favorite new package :100:

**Comment by abkfenris** [comment]
How about keeping the main list generalized, and instead of creating another repo, have a separate file in this one for different disciplines? `solid.md`, `planetary.md`, `squishy.md`...

**Comment by kinverarity1** [comment]
There is already at least one other list "wet earth" field:  https://github.com/raoulcollenteur/Python-Hydrology-Tools

Ping @raoulcollenteur

**Comment by leouieda** [comment]
@abkfenris I like the idea but I imagine the click through to sublists is gonna be very low. We already link to Awesome Geospatial and I'm sure there are others out there. We could have an "Awesome Awesome Earth and Planetary Sciences" list of lists to link these things together. Like https://github.com/sindresorhus/awesome

**Comment by rabernat** [comment]
Ok I have created a new list:
https://github.com/pangeo-data/awesome-open-climate-science
(totally incomplete, but it's a place to start)

Thanks for all your help and feedback. Let's continue to coordinate between these lists.
