### ISSUE TITLE
Consider adding link to https://github.com/r-spatial/

### ISSUE THREAD

**Issue by seasmith** [softwareunderground/awesome-open-geoscience#65]
Open-source spatial software development in the R language:

- https://github.com/r-spatial/
- https://www.r-spatial.org/ (website/blog/news)

**Comment by JesperDramsch** [comment]
Welcome @seasmith,

It would probably fit well in our geospatial category. If you would like to vouch for it, please open a PR and [check our contribution guide](/softwareunderground/awesome-open-geoscience/blob/master/contributing.md) we even have the R-badge ready to go 🥇

**Comment by JesperDramsch** [comment]
Changing link for gstat package to r-spatial in #71
