### ISSUE TITLE
Project site down: should links go to code repo or docs?

### ISSUE THREAD

**Issue by banesullivan** [softwareunderground/awesome-open-geoscience#67]
the DuMuX website is down - causing Travis to fail. Perhaps we should link to the repository instead of their website? 

https://git.iws.uni-stuttgart.de/dumux-repositories/dumux

This also raises the question on whether links here should point to the code repository (proving it's open-source) or to the documentation/homepage of the listed project

**Comment by JesperDramsch** [comment]
Good point.

I suppose an awesome repo would link heir docs in the repo?

I think linking to GitHub will make our lives a bit easier.

**Comment by banesullivan** [comment]
> I suppose an awesome repo would link heir docs in the repo?

Right?!

> I think linking to GitHub will make our lives a bit easier.

From a maintenance perspective, I definitely think so. Docs builds can fail, change domains, or go down; repositories on GitHub/GitLab/etc. are likely the most reliable

**Comment by leouieda** [comment]
> I think linking to GitHub will make our lives a bit easier.

+1
