### ISSUE TITLE
Suggestion: add Radar or GPR category

### ISSUE THREAD

**Issue by iannesbitt** [softwareunderground/awesome-open-geoscience#73]
Would it make sense to add a ground penetrating radar (GPR) category? I see no category under which open GPR processing software like [GPRPy](https://github.com/NSGeophysics/GPRPy), [RGPR](https://emanuelhuber.github.io/RGPR/), or [readgssi](https://github.com/iannesbitt/readgssi) can fit (disclaimer: readgssi is my own software, so whether or not it's awesome is arguably not my place to decide).

I would love to see a place where open GPR software is enumerated and this repository seems perfect for that purpose.

**Comment by banesullivan** [comment]
I think this is an excellent idea @iannesbitt!! I have struggled to find awesome, open-source GPR processing software (especially in Python - seeing your software has me excited!)

A place to start in regards to deciding if the software is awesome would be to see if your software and the others mentioned meet the Pull Request checklist (this is created when you make a new PR). Here are a few points I can think of:

- [ ] Project has an open-source license and is open on GitHub or a similar service
- [ ] Project has accessible documentation with examples
- [ ] Preferably more than a handful of stars to show people use the tool
- [ ] Creat a new category only if necessary

I'd say go ahead and follow the [Contributor's Guide](https://github.com/softwareunderground/awesome-open-geoscience/blob/master/contributing.md) with a new PR for **one of those softwares** (the most awesome 😄 one) while adding a new GPR section, then follow up with additional PRs for each additional software package you'd like to list.

**Comment by leouieda** [comment]
Taxonomy is really hard. I see the appeal and understand the desire. But then how do we deal with things like SimPEG and pyGIMLi which can (or could) do GPR but are not GPR exclusive? I'm not really in favor of the current "Seismic" section for this reason. But then again, listing GPR-exclusive software under "GPR" does make it easier to find...

@JesperDramsch any thoughts? I know @kwinkunks loves categorizing things :wink:

**Comment by prisae** [comment]
Agree @leouieda . Do we want to have processing, modelling & inversion, postprocessing, etc, or seismic, em, potentials, gpr, well logs, etc etc? I guess as soon as there are enough packages then a category is justified. Like for seismic. So we might consider a EM & Potentials category? Lots of packages would fall under that, and it could include GPR. Just ideas.

**Comment by iannesbitt** [comment]
@prisae I like the idea of an EM or EM & Potentials category actually. I was confining myself to just GPR before because as @leouieda points out the Seismic category is similarly specific, but I see no reason to exclude non-GPR EM software from a section containing GPR, as long as the focus is clearly laid out in the explanation text.

**Comment by emanuelhuber** [comment]
Hello @iannesbitt
Just to inform you that they fix their issues and that you can now add your software on https://github.com/softwareunderground/awesome-open-geoscience under the new category *Ground-penetrating radar* (I added RGPR to the list today).
Best,

Emanuel

**Comment by iannesbitt** [comment]
Cheers @emanuelhuber, thanks for letting me know.
