### ISSUE TITLE
Add back Digital Rocks Portal

### ISSUE THREAD

**Issue by leouieda** [softwareunderground/awesome-open-geoscience#77]
PR #76 removed the Digital Rocks Portal data repository because their SSL certificate is messed up. We should add it back eventually when the site is back up. Here is the entry:

```
- [Digital Rocks Portal](https://www.digitalrocksportal.org/) – Powerful data portal for images of varied porous micro-structures
```

**Comment by ADOUKATCHEGTWN** [comment]
In looking to learn the applications of GeopyTool
