### ISSUE TITLE
GeoStat-Framework

### ISSUE THREAD

**Issue by MuellerSeb** [softwareunderground/awesome-open-geoscience#94]
Hey there,

this is a nice collection. Maybe our [GeoStat-Framework](https://github.com/GeoStat-Framework) fits in here.
We provide a set of Python packages for geostatistical simulations:

- [GSTools](https://github.com/GeoStat-Framework/GSTools): GeoStatTools provides geostatistical tools for various purposes:
  - random field generation
  - conditioned field generation
  - incompressible random vector field generation
  - simple and ordinary kriging
  - variogram estimation and fitting
  - many readily provided and even user-defined covariance models
  - plotting and exporting routines
- [ogs5py](https://github.com/GeoStat-Framework/ogs5py): A python-API for the [OpenGeoSys 5](https://github.com/ufz/ogs5) scientific modeling package. OGS5 is an open-source, finite-element solver for thermo-hydro-mechanical-chemical processes in porous and fractured media.
- [welltestpy](https://github.com/GeoStat-Framework/welltestpy): A python-package for handling well based field campaigns with a special focus on estimating parameters of aquifer heterogeneity from standard pumping test data.
- [AnaFlow](https://github.com/GeoStat-Framework/AnaFlow): A python-package containing (semi-)analytical solutions for the groundwater flow equation with a focus on effective type curves for heterogeneous aquifers.
- [Walks](https://github.com/GeoStat-Framework/Walks): The Ministry of Random Walks provides methods for:
  - particle tracking
  - Lagrangian transport
  - travel time estimations

All these packages are working nicely together to generate workflows for simulating geostatistical setups.

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
An overview is given here: https://geostat-framework.org

**Comment by JustinGOSSES** [comment]
Looks pretty good. Please submit a pull request.

**Comment by banesullivan** [comment]
+1: I saw this post, checked out the library, and really like it!

**Comment by amoodie** [comment]
project has been added with #95.
